export const logsheetdata = {
  id: 27,
  key: '109da547-cfca-4238-87c7-8c88c034295a',
  date: '2021-11-03T00:00:00',
  operationGroupId: 1,
  operationGroupName: 'Control Room',
  alias: 'CR',
  shiftId: 1,
  shiftName: 'Morning',
  timeSlotId: 3,
  slotName: '11-13',
  slotFromTime: '11:00:00',
  slotToTime: '12:59:59',
  sectionId: 5,
  sectionName: 'Naptha Stabilizer',
  remark: '',
  operatorId: 1,
  empCode: 'CR101',
  userName: 'admin',
  isLocked: true,
  logSheetDetails: [
    {
      id: 615,
      logSheetMasterId: 27,
      tagId: 5,
      tagName: 'TR 3008',
      details: 'TOP DA-03',
      reading: 1,
      lastReading: 0,
      unitId: 3,
      unitName: 'Celcius'
    },
    {
      id: 643,
      logSheetMasterId: 27,
      tagId: 34,
      tagName: 'FQ 3045 X .025',
      details: 'CUMULATIVE NAPTHA',
      reading: 2,
      lastReading: 0,
      unitId: 2,
      unitName: 'Cubic Meter'
    },
    {
      id: 642,
      logSheetMasterId: 27,
      tagId: 35,
      tagName: 'FQ 3044X 10',
      details: 'CUMULATIVE GAS',
      reading: 3,
      lastReading: 0,
      unitId: 2,
      unitName: 'Cubic Meter'
    },
    {
      id: 641,
      logSheetMasterId: 27,
      tagId: 43,
      tagName: 'TUI 3055',
      details: 'NAPH TO B.L.',
      reading: 4,
      lastReading: 0,
      unitId: 3,
      unitName: 'Celcius'
    },
    {
      id: 640,
      logSheetMasterId: 27,
      tagId: 44,
      tagName: 'TUI-3052',
      details: 'FG HEADER',
      reading: 6,
      lastReading: 0,
      unitId: 3,
      unitName: 'Celcius'
    },
    {
      id: 639,
      logSheetMasterId: 27,
      tagId: 45,
      tagName: 'PI-3017',
      details: 'FG HEADER',
      reading: 6,
      lastReading: 0,
      unitId: 5,
      unitName: 'MBar'
    },
    {
      id: 638,
      logSheetMasterId: 27,
      tagId: 85,
      tagName: 'TUI 3047',
      details: 'INLET DA-3003',
      reading: 7,
      lastReading: 0,
      unitId: 3,
      unitName: 'Celcius'
    },
    {
      id: 637,
      logSheetMasterId: 27,
      tagId: 86,
      tagName: 'TUI 3048',
      details: 'TOP DA-3003',
      reading: 8,
      lastReading: 0,
      unitId: 3,
      unitName: 'Celcius'
    },
    {
      id: 636,
      logSheetMasterId: 27,
      tagId: 87,
      tagName: 'TUI 3053',
      details: 'DA-03 TRAY 13',
      reading: 9,
      lastReading: 0,
      unitId: 3,
      unitName: 'Celcius'
    },
    {
      id: 635,
      logSheetMasterId: 27,
      tagId: 88,
      tagName: 'TUI 3054',
      details: 'BOTTM DA-03',
      reading: 10,
      lastReading: 0,
      unitId: 3,
      unitName: 'Celcius'
    },
    {
      id: 634,
      logSheetMasterId: 27,
      tagId: 89,
      tagName: 'TUI 3049',
      details: 'EA-10 OUTLET',
      reading: 11,
      lastReading: 0,
      unitId: 3,
      unitName: 'Celcius'
    },
    {
      id: 633,
      logSheetMasterId: 27,
      tagId: 90,
      tagName: 'TUI 3050',
      details: 'INLET FA-07',
      reading: 12,
      lastReading: 0,
      unitId: 3,
      unitName: 'Celcius'
    },
    {
      id: 632,
      logSheetMasterId: 27,
      tagId: 91,
      tagName: 'TIC 3009',
      details: 'FA-07 INLET',
      reading: 13,
      lastReading: 0,
      unitId: 3,
      unitName: 'Celcius'
    },
    {
      id: 631,
      logSheetMasterId: 27,
      tagId: 92,
      tagName: 'TUI 3051',
      details: 'REFLUX DA-03',
      reading: 14,
      lastReading: 0,
      unitId: 3,
      unitName: 'Celcius'
    },
    {
      id: 644,
      logSheetMasterId: 27,
      tagId: 93,
      tagName: 'LIC-3014',
      details: 'DA-03 LEVEL',
      reading: 15,
      lastReading: 0,
      unitId: 1,
      unitName: 'Per Hour Cubic Meter'
    },
    {
      id: 630,
      logSheetMasterId: 27,
      tagId: 94,
      tagName: 'FQI 3045 X 0.025',
      details: 'NAPHTHA FLOW',
      reading: 16,
      lastReading: 0,
      unitId: 1,
      unitName: 'Per Hour Cubic Meter'
    },
    {
      id: 628,
      logSheetMasterId: 27,
      tagId: 95,
      tagName: 'PIC 3016',
      details: 'FA-07 PRESS',
      reading: 17,
      lastReading: 0,
      unitId: 4,
      unitName: 'Bar'
    },
    {
      id: 627,
      logSheetMasterId: 27,
      tagId: 96,
      tagName: 'LIC-3015',
      details: 'FA-07 LEVEL',
      reading: 18,
      lastReading: 0,
      unitId: 1,
      unitName: 'Per Hour Cubic Meter'
    },
    {
      id: 626,
      logSheetMasterId: 27,
      tagId: 97,
      tagName: 'FIC-3013 X 0.15',
      details: 'DA-03 REFLUX',
      reading: 19,
      lastReading: 0,
      unitId: 1,
      unitName: 'Per Hour Cubic Meter'
    },
    {
      id: 625,
      logSheetMasterId: 27,
      tagId: 98,
      tagName: 'FR-3036 X 0.6',
      details: 'DA-03 INLET',
      reading: 20,
      lastReading: 0,
      unitId: 1,
      unitName: 'Per Hour Cubic Meter'
    },
    {
      id: 624,
      logSheetMasterId: 27,
      tagId: 99,
      tagName: 'PI-3035',
      details: 'FA-05 PRESS',
      reading: 21,
      lastReading: 0,
      unitId: 4,
      unitName: 'Bar'
    },
    {
      id: 623,
      logSheetMasterId: 27,
      tagId: 100,
      tagName: 'TUI 3067',
      details: 'DISCH GB-01',
      reading: 22,
      lastReading: 0,
      unitId: 3,
      unitName: 'Celcius'
    },
    {
      id: 622,
      logSheetMasterId: 27,
      tagId: 101,
      tagName: 'FR 3031 X 170',
      details: 'DISCH BG-01 & S',
      reading: 23,
      lastReading: 0,
      unitId: 1,
      unitName: 'Per Hour Cubic Meter'
    },
    {
      id: 621,
      logSheetMasterId: 27,
      tagId: 102,
      tagName: 'TUI-3045',
      details: 'DISCH GB-01 S',
      reading: 24,
      lastReading: 0,
      unitId: 3,
      unitName: 'Celcius'
    },
    {
      id: 620,
      logSheetMasterId: 27,
      tagId: 103,
      tagName: 'TUI-3046',
      details: 'FA-06 OUTLET',
      reading: 25,
      lastReading: 0,
      unitId: 3,
      unitName: 'Celcius'
    },
    {
      id: 619,
      logSheetMasterId: 27,
      tagId: 104,
      tagName: 'PIC 3015',
      details: 'FA-06 PRESS',
      reading: 26,
      lastReading: 0,
      unitId: 4,
      unitName: 'Bar'
    },
    {
      id: 618,
      logSheetMasterId: 27,
      tagId: 105,
      tagName: 'LIC 3012',
      details: 'FA-06 NAPHTHA',
      reading: 27,
      lastReading: 0,
      unitId: 1,
      unitName: 'Per Hour Cubic Meter'
    },
    {
      id: 617,
      logSheetMasterId: 27,
      tagId: 106,
      tagName: 'FR 3032 X 170',
      details: 'FA-06 OUTLET',
      reading: 28,
      lastReading: 0,
      unitId: 1,
      unitName: 'Per Hour Cubic Meter'
    },
    {
      id: 616,
      logSheetMasterId: 27,
      tagId: 107,
      tagName: 'FI-3033 X 170',
      details: 'FA-05 SPILL BACK',
      reading: 29,
      lastReading: 0,
      unitId: 1,
      unitName: 'Per Hour Cubic Meter'
    },
    {
      id: 629,
      logSheetMasterId: 27,
      tagId: 108,
      tagName: 'GB 3001 & 5 LOAD',
      details: 'NULL',
      reading: 30,
      lastReading: 0,
      unitId: 1,
      unitName: 'Per Hour Cubic Meter'
    },
    {
      id: 645,
      logSheetMasterId: 27,
      tagId: 109,
      tagName: 'FQI-3044 X 10',
      details: 'GAS PROD',
      reading: 31,
      lastReading: 0,
      unitId: 1,
      unitName: 'Per Hour Cubic Meter'
    }
  ]
};
